runtime: nodejs14

service: default

handlers:
  - url: /static
    static_dir: client/build/static

  - url: /(.*\.(json|ico|js))$
    static_files: client/build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: client/build/index.html
    upload: client/build/index.html